<?php

define('REQUEST_URI', $_SERVER["REQUEST_URI"]);
define('API_URL', $_SERVER["SCRIPT_URL"].'api');
    
?><!DOCTYPE html>
<html>
  <head>
  
    <title>Offices API</title>
  
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <link href='//fonts.googleapis.com/css?family=Chivo:900' rel='stylesheet' type='text/css'>
    
    <link rel="stylesheet" type="text/css" href="<?php echo API_URL; ?>/templates/tactile/stylesheets/stylesheet.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo API_URL; ?>/templates/tactile/stylesheets/pygment_trac.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo API_URL; ?>/templates/tactile/stylesheets/print.css" media="print" />
    
    <link href="<?php echo API_URL; ?>/css/bootstrap-responsive.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="<?php echo API_URL; ?>/css/swagger.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo API_URL; ?>/css/hightlight.default.css" media="screen" />
    
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js"></script>
    <script src='<?php echo API_URL; ?>/js/shred.bundle.js' type='text/javascript' /></script>
    <script src='<?php echo API_URL; ?>/js/jquery-1.8.0.min.js' type='text/javascript'></script>
    <script src='<?php echo API_URL; ?>/js/jquery.slideto.min.js' type='text/javascript'></script>
    <script src='<?php echo API_URL; ?>/js/jquery.wiggle.min.js' type='text/javascript'></script>
    <script src='<?php echo API_URL; ?>/js/jquery.ba-bbq.min.js' type='text/javascript'></script>
    <script src='<?php echo API_URL; ?>/js/handlebars-1.0.rc.1.js' type='text/javascript'></script>
    <script src='<?php echo API_URL; ?>/js/underscore-min.js' type='text/javascript'></script>
    <script src='<?php echo API_URL; ?>/js/backbone-min.js' type='text/javascript'></script>
    <script src='<?php echo API_URL; ?>/js/swagger.js' type='text/javascript'></script>
    <script src='<?php echo API_URL; ?>/js/swagger-ui.js' type='text/javascript'></script>
    <script src='<?php echo API_URL; ?>/js/highlight.7.3.pack.js' type='text/javascript'></script>
    <script src='<?php echo API_URL; ?>/js/mustache.js' type='text/javascript'></script>
    <script src='<?php echo API_URL; ?>/js/injector.js' type='text/javascript'></script>
    <script src='<?php echo API_URL; ?>/js/utilities.js' type='text/javascript'></script>
   
    <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
           
    <script type="text/javascript">
    
        var $Path = 'offices';

        $(function () {
            window.swaggerUi = new SwaggerUi({
                url: "<?php echo REQUEST_URI; ?>" + $Path,
                dom_id: "swagger-ui-container",
                supportedSubmitMethods: ['get', 'post', 'put', 'delete'],
                onComplete: function(swaggerApi, swaggerUi){
                if(console) {
                    console.log("Loaded SwaggerUI")
                    }
            
                $('pre code').each(function(i, e) {hljs.highlightBlock(e)});
                },
                onFailure: function(data) {
                if(console) {
                    console.log("Unable to Load SwaggerUI");
                    console.log(data);
                    }
                },
                docExpansion: "none"
            });
            window.swaggerUi.load();
        });
    </script>    
    
  </head>

  <body>
    <div id="container">
      <div class="inner">

        <header>
          <h1>Offices API</h1>
          <h2>This is a <a href="//simple-api.github.io/central/">simple api</a> for offices.</h2>
        </header>

        <section id="main_content">
          
            <div class="swagger-shell" style="width: 600px;"> 
                <div id="swagger-ui-container" class="swagger-ui-wrap"></div>
            </div>

        </section>

        <footer>
          Offices API is maintained by <a href="//github.com/kinlane">kinlane</a><br>
          This page was generated by <a href="//pages.github.com">GitHub Pages</a>. Tactile theme by <a href="//twitter.com/jasonlong">Jason Long</a>.
        </footer>

        
      </div>
    </div>
  </body>
</html>
